apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/acme-challenge-type: http01
    certmanager.k8s.io/cluster-issuer: letsencrypt
  name: mortgagefixedrates-ingress
spec:
  tls:
  - hosts:
    - fixedrates.mortgage.iliasjennane.com
    secretName: letsencrypt
  rules:
  - host: fixedrates.mortgage.iliasjennane.com
    http:
      paths:
      - backend:
          serviceName: mortgagefixedrates
          servicePort: 80