apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-ingress
spec:
  tls:
  - hosts:
    - ui.mortgage.iliasjennane.com
    secretName: letsencrypt
  rules:
  - host: ui.mortgage.iliasjennane.com
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-{{ .Chart.Name }}
          servicePort: 80