apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-config
data:
  ocpApimSubscriptionKey: "{{ .Values.config.apikey }}"
  ocpApimTrace: "{{ .Values.config.apimtrace }}"