apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
    - port : 443
      name: https
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}