apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    #certmanager.k8s.io/acme-challenge-type: http01
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: {{ .Release.Name }}-{{ .Chart.Name }}-ingress
spec:
  tls:
  - hosts:
    - mortgagerateaverages.iliasjennane.com
    secretName: mortgagerateaverages-letsencrypt-prod
  rules:
  - host: mortgagerateaverages.iliasjennane.com
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-{{ .Chart.Name }}
          servicePort: 80


